// AUTO-GENERATED by gen_overrides.py -- do not edit by hand.
// Each override emits the node line and manually walks its children so that
// indentation (self.indent) and child nodes render correctly.
use rustpython_parser::ast::{self, *};
use rustpython_parser::ast::Visitor;
use rustpython_parser::text_size::TextRange;

/// Minimal Display for a `Constant` leaf.
struct ConstantDisplay<'a>(&'a Constant);
impl std::fmt::Display for ConstantDisplay<'_> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self.0 {
            Constant::None => write!(f, "None"),
            Constant::Ellipsis => write!(f, "Ellipsis"),
            Constant::Bool(b) => write!(f, "{b}"),
            Constant::Str(s) => write!(f, "{s:?}"),
            Constant::Bytes(b) => write!(f, "b{} bytes", b.len()),
            Constant::Int(i) => write!(f, "{i}"),
            Constant::Float(x) => write!(f, "{x}"),
            Constant::Complex { real, imag } => write!(f, "{real}+{imag}i"),
            Constant::Tuple(items) => write!(f, "({} items)", items.len()),
        }
    }
}


impl Visitor<TextRange> for crate::DlpDumper {

    fn visit_alias(&mut self, mut node: Alias<TextRange>) {
        self.emit(Alias::<TextRange>::NAME, node.range(), Some(&[
            format_args!("{f} = {v:?}", f = "name", v = node.name.as_str()),
        ]));
    }

    fn visit_arg(&mut self, mut node: Arg<TextRange>) {
        self.emit(Arg::<TextRange>::NAME, node.range(), Some(&[
            format_args!("{f} = {v:?}", f = "arg", v = node.arg.as_str()),
        ]));
        self.indent += 1;
            if let Some(value) = node.annotation {
                self.visit_expr(*value);
            }
        self.indent -= 1;
    }

    fn visit_arguments(&mut self, mut node: Arguments<TextRange>) {
        self.emit(Arguments::<TextRange>::NAME, node.range(), None);
        self.indent += 1;
            for value in std::mem::take(&mut node.posonlyargs) {
                    self.emit(ArgWithDefault::<TextRange>::NAME, value.range(), None);
                    self.indent += 1;
                    self.visit_arg(value.def);
                    if let Some(value) = value.default {
                        self.visit_expr(*value);
                    }
                    self.indent -= 1;
            }
            for value in std::mem::take(&mut node.args) {
                    self.emit(ArgWithDefault::<TextRange>::NAME, value.range(), None);
                    self.indent += 1;
                    self.visit_arg(value.def);
                    if let Some(value) = value.default {
                        self.visit_expr(*value);
                    }
                    self.indent -= 1;
            }
            if let Some(value) = node.vararg {
                self.visit_arg(*value);
            }
            for value in std::mem::take(&mut node.kwonlyargs) {
                    self.emit(ArgWithDefault::<TextRange>::NAME, value.range(), None);
                    self.indent += 1;
                    self.visit_arg(value.def);
                    if let Some(value) = value.default {
                        self.visit_expr(*value);
                    }
                    self.indent -= 1;
            }
            if let Some(value) = node.kwarg {
                self.visit_arg(*value);
            }
        self.indent -= 1;
    }

    fn visit_comprehension(&mut self, mut node: Comprehension<TextRange>) {
        self.emit(Comprehension::<TextRange>::NAME, node.range(), Some(&[
            format_args!("{f} = {v}", f = "is_async", v = node.is_async),
        ]));
        self.indent += 1;
            self.visit_expr(node.target);
            self.visit_expr(node.iter);
            for value in std::mem::take(&mut node.ifs) {
                self.visit_expr(value);
            }
        self.indent -= 1;
    }

    fn visit_excepthandler_except_handler(&mut self, mut node: ExceptHandlerExceptHandler<TextRange>) {
        self.emit(ExceptHandlerExceptHandler::<TextRange>::NAME, node.range(), None);
        self.indent += 1;
            if let Some(value) = node.type_ {
                self.visit_expr(*value);
            }
            for value in std::mem::take(&mut node.body) {
                self.visit_stmt(value);
            }
        self.indent -= 1;
    }

    fn visit_expr_attribute(&mut self, mut node: ExprAttribute<TextRange>) {
        self.emit(ExprAttribute::<TextRange>::NAME, node.range(), Some(&[
            format_args!("{f} = {v:?}", f = "attr", v = node.attr.as_str()),
            format_args!("{f} = {v:?}", f = "ctx", v = node.ctx),
        ]));
        self.indent += 1;
            self.visit_expr(*node.value);
        self.indent -= 1;
    }

    fn visit_expr_await(&mut self, mut node: ExprAwait<TextRange>) {
        self.emit(ExprAwait::<TextRange>::NAME, node.range(), None);
        self.indent += 1;
            self.visit_expr(*node.value);
        self.indent -= 1;
    }

    fn visit_expr_bin_op(&mut self, mut node: ExprBinOp<TextRange>) {
        self.emit(ExprBinOp::<TextRange>::NAME, node.range(), Some(&[
            format_args!("{f} = {v:?}", f = "op", v = node.op),
        ]));
        self.indent += 1;
            self.visit_expr(*node.left);
            self.visit_expr(*node.right);
        self.indent -= 1;
    }

    fn visit_expr_bool_op(&mut self, mut node: ExprBoolOp<TextRange>) {
        self.emit(ExprBoolOp::<TextRange>::NAME, node.range(), Some(&[
            format_args!("{f} = {v:?}", f = "op", v = node.op),
        ]));
        self.indent += 1;
            for value in std::mem::take(&mut node.values) {
                self.visit_expr(value);
            }
        self.indent -= 1;
    }

    fn visit_expr_call(&mut self, mut node: ExprCall<TextRange>) {
        self.emit(ExprCall::<TextRange>::NAME, node.range(), None);
        self.indent += 1;
            self.visit_expr(*node.func);
            for value in std::mem::take(&mut node.args) {
                self.visit_expr(value);
            }
            for value in std::mem::take(&mut node.keywords) {
                self.visit_keyword(value);
            }
        self.indent -= 1;
    }

    fn visit_expr_compare(&mut self, mut node: ExprCompare<TextRange>) {
        self.emit(ExprCompare::<TextRange>::NAME, node.range(), None);
        self.indent += 1;
            self.visit_expr(*node.left);
            for value in std::mem::take(&mut node.comparators) {
                self.visit_expr(value);
            }
        self.indent -= 1;
    }

    fn visit_expr_constant(&mut self, mut node: ExprConstant<TextRange>) {
        self.emit(ExprConstant::<TextRange>::NAME, node.range(), Some(&[
            format_args!("{f} = {v}", f = "value", v = ConstantDisplay(&node.value)),
        ]));
    }

    fn visit_expr_dict(&mut self, mut node: ExprDict<TextRange>) {
        self.emit(ExprDict::<TextRange>::NAME, node.range(), None);
        self.indent += 1;
            for value in std::mem::take(&mut node.keys) {
                if let Some(value) = value {
                    self.visit_expr(value);
                }
            }
            for value in std::mem::take(&mut node.values) {
                self.visit_expr(value);
            }
        self.indent -= 1;
    }

    fn visit_expr_dict_comp(&mut self, mut node: ExprDictComp<TextRange>) {
        self.emit(ExprDictComp::<TextRange>::NAME, node.range(), None);
        self.indent += 1;
            self.visit_expr(*node.key);
            self.visit_expr(*node.value);
            for value in std::mem::take(&mut node.generators) {
                self.visit_comprehension(value);
            }
        self.indent -= 1;
    }

    fn visit_expr_formatted_value(&mut self, mut node: ExprFormattedValue<TextRange>) {
        self.emit(ExprFormattedValue::<TextRange>::NAME, node.range(), Some(&[
            format_args!("{f} = {v:?}", f = "conversion", v = node.conversion),
        ]));
        self.indent += 1;
            self.visit_expr(*node.value);
            if let Some(value) = node.format_spec {
                self.visit_expr(*value);
            }
        self.indent -= 1;
    }

    fn visit_expr_generator_exp(&mut self, mut node: ExprGeneratorExp<TextRange>) {
        self.emit(ExprGeneratorExp::<TextRange>::NAME, node.range(), None);
        self.indent += 1;
            self.visit_expr(*node.elt);
            for value in std::mem::take(&mut node.generators) {
                self.visit_comprehension(value);
            }
        self.indent -= 1;
    }

    fn visit_expr_if_exp(&mut self, mut node: ExprIfExp<TextRange>) {
        self.emit(ExprIfExp::<TextRange>::NAME, node.range(), None);
        self.indent += 1;
            self.visit_expr(*node.test);
            self.visit_expr(*node.body);
            self.visit_expr(*node.orelse);
        self.indent -= 1;
    }

    fn visit_expr_joined_str(&mut self, mut node: ExprJoinedStr<TextRange>) {
        self.emit(ExprJoinedStr::<TextRange>::NAME, node.range(), None);
        self.indent += 1;
            for value in std::mem::take(&mut node.values) {
                self.visit_expr(value);
            }
        self.indent -= 1;
    }

    fn visit_expr_lambda(&mut self, mut node: ExprLambda<TextRange>) {
        self.emit(ExprLambda::<TextRange>::NAME, node.range(), None);
        self.indent += 1;
            self.visit_arguments(*node.args);
            self.visit_expr(*node.body);
        self.indent -= 1;
    }

    fn visit_expr_list(&mut self, mut node: ExprList<TextRange>) {
        self.emit(ExprList::<TextRange>::NAME, node.range(), Some(&[
            format_args!("{f} = {v:?}", f = "ctx", v = node.ctx),
        ]));
        self.indent += 1;
            for value in std::mem::take(&mut node.elts) {
                self.visit_expr(value);
            }
        self.indent -= 1;
    }

    fn visit_expr_list_comp(&mut self, mut node: ExprListComp<TextRange>) {
        self.emit(ExprListComp::<TextRange>::NAME, node.range(), None);
        self.indent += 1;
            self.visit_expr(*node.elt);
            for value in std::mem::take(&mut node.generators) {
                self.visit_comprehension(value);
            }
        self.indent -= 1;
    }

    fn visit_expr_name(&mut self, mut node: ExprName<TextRange>) {
        self.emit(ExprName::<TextRange>::NAME, node.range(), Some(&[
            format_args!("{f} = {v:?}", f = "id", v = node.id.as_str()),
            format_args!("{f} = {v:?}", f = "ctx", v = node.ctx),
        ]));
    }

    fn visit_expr_named_expr(&mut self, mut node: ExprNamedExpr<TextRange>) {
        self.emit(ExprNamedExpr::<TextRange>::NAME, node.range(), None);
        self.indent += 1;
            self.visit_expr(*node.target);
            self.visit_expr(*node.value);
        self.indent -= 1;
    }

    fn visit_expr_set(&mut self, mut node: ExprSet<TextRange>) {
        self.emit(ExprSet::<TextRange>::NAME, node.range(), None);
        self.indent += 1;
            for value in std::mem::take(&mut node.elts) {
                self.visit_expr(value);
            }
        self.indent -= 1;
    }

    fn visit_expr_set_comp(&mut self, mut node: ExprSetComp<TextRange>) {
        self.emit(ExprSetComp::<TextRange>::NAME, node.range(), None);
        self.indent += 1;
            self.visit_expr(*node.elt);
            for value in std::mem::take(&mut node.generators) {
                self.visit_comprehension(value);
            }
        self.indent -= 1;
    }

    fn visit_expr_slice(&mut self, mut node: ExprSlice<TextRange>) {
        self.emit(ExprSlice::<TextRange>::NAME, node.range(), None);
        self.indent += 1;
            if let Some(value) = node.lower {
                self.visit_expr(*value);
            }
            if let Some(value) = node.upper {
                self.visit_expr(*value);
            }
            if let Some(value) = node.step {
                self.visit_expr(*value);
            }
        self.indent -= 1;
    }

    fn visit_expr_starred(&mut self, mut node: ExprStarred<TextRange>) {
        self.emit(ExprStarred::<TextRange>::NAME, node.range(), Some(&[
            format_args!("{f} = {v:?}", f = "ctx", v = node.ctx),
        ]));
        self.indent += 1;
            self.visit_expr(*node.value);
        self.indent -= 1;
    }

    fn visit_expr_subscript(&mut self, mut node: ExprSubscript<TextRange>) {
        self.emit(ExprSubscript::<TextRange>::NAME, node.range(), Some(&[
            format_args!("{f} = {v:?}", f = "ctx", v = node.ctx),
        ]));
        self.indent += 1;
            self.visit_expr(*node.value);
            self.visit_expr(*node.slice);
        self.indent -= 1;
    }

    fn visit_expr_tuple(&mut self, mut node: ExprTuple<TextRange>) {
        self.emit(ExprTuple::<TextRange>::NAME, node.range(), Some(&[
            format_args!("{f} = {v:?}", f = "ctx", v = node.ctx),
        ]));
        self.indent += 1;
            for value in std::mem::take(&mut node.elts) {
                self.visit_expr(value);
            }
        self.indent -= 1;
    }

    fn visit_expr_unary_op(&mut self, mut node: ExprUnaryOp<TextRange>) {
        self.emit(ExprUnaryOp::<TextRange>::NAME, node.range(), Some(&[
            format_args!("{f} = {v:?}", f = "op", v = node.op),
        ]));
        self.indent += 1;
            self.visit_expr(*node.operand);
        self.indent -= 1;
    }

    fn visit_expr_yield(&mut self, mut node: ExprYield<TextRange>) {
        self.emit(ExprYield::<TextRange>::NAME, node.range(), None);
        self.indent += 1;
            if let Some(value) = node.value {
                self.visit_expr(*value);
            }
        self.indent -= 1;
    }

    fn visit_expr_yield_from(&mut self, mut node: ExprYieldFrom<TextRange>) {
        self.emit(ExprYieldFrom::<TextRange>::NAME, node.range(), None);
        self.indent += 1;
            self.visit_expr(*node.value);
        self.indent -= 1;
    }

    fn visit_keyword(&mut self, mut node: Keyword<TextRange>) {
        self.emit(Keyword::<TextRange>::NAME, node.range(), None);
        self.indent += 1;
            self.visit_expr(node.value);
        self.indent -= 1;
    }

    fn visit_match_case(&mut self, mut node: MatchCase<TextRange>) {
        self.emit(MatchCase::<TextRange>::NAME, node.range(), None);
        self.indent += 1;
            self.visit_pattern(node.pattern);
            if let Some(value) = node.guard {
                self.visit_expr(*value);
            }
            for value in std::mem::take(&mut node.body) {
                self.visit_stmt(value);
            }
        self.indent -= 1;
    }

    fn visit_pattern_match_as(&mut self, mut node: PatternMatchAs<TextRange>) {
        self.emit(PatternMatchAs::<TextRange>::NAME, node.range(), None);
        self.indent += 1;
            if let Some(value) = node.pattern {
                self.visit_pattern(*value);
            }
        self.indent -= 1;
    }

    fn visit_pattern_match_class(&mut self, mut node: PatternMatchClass<TextRange>) {
        self.emit(PatternMatchClass::<TextRange>::NAME, node.range(), None);
        self.indent += 1;
            self.visit_expr(*node.cls);
            for value in std::mem::take(&mut node.patterns) {
                self.visit_pattern(value);
            }
            for value in std::mem::take(&mut node.kwd_patterns) {
                self.visit_pattern(value);
            }
        self.indent -= 1;
    }

    fn visit_pattern_match_mapping(&mut self, mut node: PatternMatchMapping<TextRange>) {
        self.emit(PatternMatchMapping::<TextRange>::NAME, node.range(), None);
        self.indent += 1;
            for value in std::mem::take(&mut node.keys) {
                self.visit_expr(value);
            }
            for value in std::mem::take(&mut node.patterns) {
                self.visit_pattern(value);
            }
        self.indent -= 1;
    }

    fn visit_pattern_match_or(&mut self, mut node: PatternMatchOr<TextRange>) {
        self.emit(PatternMatchOr::<TextRange>::NAME, node.range(), None);
        self.indent += 1;
            for value in std::mem::take(&mut node.patterns) {
                self.visit_pattern(value);
            }
        self.indent -= 1;
    }

    fn visit_pattern_match_sequence(&mut self, mut node: PatternMatchSequence<TextRange>) {
        self.emit(PatternMatchSequence::<TextRange>::NAME, node.range(), None);
        self.indent += 1;
            for value in std::mem::take(&mut node.patterns) {
                self.visit_pattern(value);
            }
        self.indent -= 1;
    }

    fn visit_pattern_match_singleton(&mut self, mut node: PatternMatchSingleton<TextRange>) {
        self.emit(PatternMatchSingleton::<TextRange>::NAME, node.range(), Some(&[
            format_args!("{f} = {v}", f = "value", v = ConstantDisplay(&node.value)),
        ]));
    }

    fn visit_pattern_match_star(&mut self, mut node: PatternMatchStar<TextRange>) {
        self.emit(PatternMatchStar::<TextRange>::NAME, node.range(), None);
    }

    fn visit_pattern_match_value(&mut self, mut node: PatternMatchValue<TextRange>) {
        self.emit(PatternMatchValue::<TextRange>::NAME, node.range(), None);
        self.indent += 1;
            self.visit_expr(*node.value);
        self.indent -= 1;
    }

    fn visit_stmt_ann_assign(&mut self, mut node: StmtAnnAssign<TextRange>) {
        self.emit(StmtAnnAssign::<TextRange>::NAME, node.range(), Some(&[
            format_args!("{f} = {v}", f = "simple", v = node.simple),
        ]));
        self.indent += 1;
            self.visit_expr(*node.target);
            self.visit_expr(*node.annotation);
            if let Some(value) = node.value {
                self.visit_expr(*value);
            }
        self.indent -= 1;
    }

    fn visit_stmt_assert(&mut self, mut node: StmtAssert<TextRange>) {
        self.emit(StmtAssert::<TextRange>::NAME, node.range(), None);
        self.indent += 1;
            self.visit_expr(*node.test);
            if let Some(value) = node.msg {
                self.visit_expr(*value);
            }
        self.indent -= 1;
    }

    fn visit_stmt_assign(&mut self, mut node: StmtAssign<TextRange>) {
        self.emit(StmtAssign::<TextRange>::NAME, node.range(), None);
        self.indent += 1;
            for value in std::mem::take(&mut node.targets) {
                self.visit_expr(value);
            }
            self.visit_expr(*node.value);
        self.indent -= 1;
    }

    fn visit_stmt_async_for(&mut self, mut node: StmtAsyncFor<TextRange>) {
        self.emit(StmtAsyncFor::<TextRange>::NAME, node.range(), None);
        self.indent += 1;
            self.visit_expr(*node.target);
            self.visit_expr(*node.iter);
            for value in std::mem::take(&mut node.body) {
                self.visit_stmt(value);
            }
            for value in std::mem::take(&mut node.orelse) {
                self.visit_stmt(value);
            }
        self.indent -= 1;
    }

    fn visit_stmt_async_function_def(&mut self, mut node: StmtAsyncFunctionDef<TextRange>) {
        self.emit(StmtAsyncFunctionDef::<TextRange>::NAME, node.range(), Some(&[
            format_args!("{f} = {v:?}", f = "name", v = node.name.as_str()),
        ]));
        self.indent += 1;
            self.visit_arguments(*node.args);
            for value in std::mem::take(&mut node.body) {
                self.visit_stmt(value);
            }
            for value in std::mem::take(&mut node.decorator_list) {
                self.visit_expr(value);
            }
            if let Some(value) = node.returns {
                self.visit_expr(*value);
            }
            for value in std::mem::take(&mut node.type_params) {
                self.visit_type_param(value);
            }
        self.indent -= 1;
    }

    fn visit_stmt_async_with(&mut self, mut node: StmtAsyncWith<TextRange>) {
        self.emit(StmtAsyncWith::<TextRange>::NAME, node.range(), None);
        self.indent += 1;
            for value in std::mem::take(&mut node.items) {
                self.visit_withitem(value);
            }
            for value in std::mem::take(&mut node.body) {
                self.visit_stmt(value);
            }
        self.indent -= 1;
    }

    fn visit_stmt_aug_assign(&mut self, mut node: StmtAugAssign<TextRange>) {
        self.emit(StmtAugAssign::<TextRange>::NAME, node.range(), Some(&[
            format_args!("{f} = {v:?}", f = "op", v = node.op),
        ]));
        self.indent += 1;
            self.visit_expr(*node.target);
            self.visit_expr(*node.value);
        self.indent -= 1;
    }

    fn visit_stmt_break(&mut self, mut node: StmtBreak<TextRange>) {
        self.emit(StmtBreak::<TextRange>::NAME, node.range(), None);
    }

    fn visit_stmt_class_def(&mut self, mut node: StmtClassDef<TextRange>) {
        self.emit(StmtClassDef::<TextRange>::NAME, node.range(), Some(&[
            format_args!("{f} = {v:?}", f = "name", v = node.name.as_str()),
        ]));
        self.indent += 1;
            for value in std::mem::take(&mut node.bases) {
                self.visit_expr(value);
            }
            for value in std::mem::take(&mut node.keywords) {
                self.visit_keyword(value);
            }
            for value in std::mem::take(&mut node.body) {
                self.visit_stmt(value);
            }
            for value in std::mem::take(&mut node.decorator_list) {
                self.visit_expr(value);
            }
            for value in std::mem::take(&mut node.type_params) {
                self.visit_type_param(value);
            }
        self.indent -= 1;
    }

    fn visit_stmt_continue(&mut self, mut node: StmtContinue<TextRange>) {
        self.emit(StmtContinue::<TextRange>::NAME, node.range(), None);
    }

    fn visit_stmt_delete(&mut self, mut node: StmtDelete<TextRange>) {
        self.emit(StmtDelete::<TextRange>::NAME, node.range(), None);
        self.indent += 1;
            for value in std::mem::take(&mut node.targets) {
                self.visit_expr(value);
            }
        self.indent -= 1;
    }

    fn visit_stmt_expr(&mut self, mut node: StmtExpr<TextRange>) {
        self.emit(StmtExpr::<TextRange>::NAME, node.range(), None);
        self.indent += 1;
            self.visit_expr(*node.value);
        self.indent -= 1;
    }

    fn visit_stmt_for(&mut self, mut node: StmtFor<TextRange>) {
        self.emit(StmtFor::<TextRange>::NAME, node.range(), None);
        self.indent += 1;
            self.visit_expr(*node.target);
            self.visit_expr(*node.iter);
            for value in std::mem::take(&mut node.body) {
                self.visit_stmt(value);
            }
            for value in std::mem::take(&mut node.orelse) {
                self.visit_stmt(value);
            }
        self.indent -= 1;
    }

    fn visit_stmt_function_def(&mut self, mut node: StmtFunctionDef<TextRange>) {
        self.emit(StmtFunctionDef::<TextRange>::NAME, node.range(), Some(&[
            format_args!("{f} = {v:?}", f = "name", v = node.name.as_str()),
        ]));
        self.indent += 1;
            self.visit_arguments(*node.args);
            for value in std::mem::take(&mut node.body) {
                self.visit_stmt(value);
            }
            for value in std::mem::take(&mut node.decorator_list) {
                self.visit_expr(value);
            }
            if let Some(value) = node.returns {
                self.visit_expr(*value);
            }
            for value in std::mem::take(&mut node.type_params) {
                self.visit_type_param(value);
            }
        self.indent -= 1;
    }

    fn visit_stmt_global(&mut self, mut node: StmtGlobal<TextRange>) {
        self.emit(StmtGlobal::<TextRange>::NAME, node.range(), None);
    }

    fn visit_stmt_if(&mut self, mut node: StmtIf<TextRange>) {
        self.emit(StmtIf::<TextRange>::NAME, node.range(), None);
        self.indent += 1;
            self.visit_expr(*node.test);
            for value in std::mem::take(&mut node.body) {
                self.visit_stmt(value);
            }
            for value in std::mem::take(&mut node.orelse) {
                self.visit_stmt(value);
            }
        self.indent -= 1;
    }

    fn visit_stmt_import(&mut self, mut node: StmtImport<TextRange>) {
        self.emit(StmtImport::<TextRange>::NAME, node.range(), None);
        self.indent += 1;
            for value in std::mem::take(&mut node.names) {
                self.visit_alias(value);
            }
        self.indent -= 1;
    }

    fn visit_stmt_import_from(&mut self, mut node: StmtImportFrom<TextRange>) {
        self.emit(StmtImportFrom::<TextRange>::NAME, node.range(), None);
        self.indent += 1;
            for value in std::mem::take(&mut node.names) {
                self.visit_alias(value);
            }
        self.indent -= 1;
    }

    fn visit_stmt_match(&mut self, mut node: StmtMatch<TextRange>) {
        self.emit(StmtMatch::<TextRange>::NAME, node.range(), None);
        self.indent += 1;
            self.visit_expr(*node.subject);
            for value in std::mem::take(&mut node.cases) {
                self.visit_match_case(value);
            }
        self.indent -= 1;
    }

    fn visit_stmt_nonlocal(&mut self, mut node: StmtNonlocal<TextRange>) {
        self.emit(StmtNonlocal::<TextRange>::NAME, node.range(), None);
    }

    fn visit_stmt_pass(&mut self, mut node: StmtPass<TextRange>) {
        self.emit(StmtPass::<TextRange>::NAME, node.range(), None);
    }

    fn visit_stmt_raise(&mut self, mut node: StmtRaise<TextRange>) {
        self.emit(StmtRaise::<TextRange>::NAME, node.range(), None);
        self.indent += 1;
            if let Some(value) = node.exc {
                self.visit_expr(*value);
            }
            if let Some(value) = node.cause {
                self.visit_expr(*value);
            }
        self.indent -= 1;
    }

    fn visit_stmt_return(&mut self, mut node: StmtReturn<TextRange>) {
        self.emit(StmtReturn::<TextRange>::NAME, node.range(), None);
        self.indent += 1;
            if let Some(value) = node.value {
                self.visit_expr(*value);
            }
        self.indent -= 1;
    }

    fn visit_stmt_try(&mut self, mut node: StmtTry<TextRange>) {
        self.emit(StmtTry::<TextRange>::NAME, node.range(), None);
        self.indent += 1;
            for value in std::mem::take(&mut node.body) {
                self.visit_stmt(value);
            }
            for value in std::mem::take(&mut node.handlers) {
                self.visit_excepthandler(value);
            }
            for value in std::mem::take(&mut node.orelse) {
                self.visit_stmt(value);
            }
            for value in std::mem::take(&mut node.finalbody) {
                self.visit_stmt(value);
            }
        self.indent -= 1;
    }

    fn visit_stmt_try_star(&mut self, mut node: StmtTryStar<TextRange>) {
        self.emit(StmtTryStar::<TextRange>::NAME, node.range(), None);
        self.indent += 1;
            for value in std::mem::take(&mut node.body) {
                self.visit_stmt(value);
            }
            for value in std::mem::take(&mut node.handlers) {
                self.visit_excepthandler(value);
            }
            for value in std::mem::take(&mut node.orelse) {
                self.visit_stmt(value);
            }
            for value in std::mem::take(&mut node.finalbody) {
                self.visit_stmt(value);
            }
        self.indent -= 1;
    }

    fn visit_stmt_type_alias(&mut self, mut node: StmtTypeAlias<TextRange>) {
        self.emit(StmtTypeAlias::<TextRange>::NAME, node.range(), None);
        self.indent += 1;
            self.visit_expr(*node.name);
            for value in std::mem::take(&mut node.type_params) {
                self.visit_type_param(value);
            }
            self.visit_expr(*node.value);
        self.indent -= 1;
    }

    fn visit_stmt_while(&mut self, mut node: StmtWhile<TextRange>) {
        self.emit(StmtWhile::<TextRange>::NAME, node.range(), None);
        self.indent += 1;
            self.visit_expr(*node.test);
            for value in std::mem::take(&mut node.body) {
                self.visit_stmt(value);
            }
            for value in std::mem::take(&mut node.orelse) {
                self.visit_stmt(value);
            }
        self.indent -= 1;
    }

    fn visit_stmt_with(&mut self, mut node: StmtWith<TextRange>) {
        self.emit(StmtWith::<TextRange>::NAME, node.range(), None);
        self.indent += 1;
            for value in std::mem::take(&mut node.items) {
                self.visit_withitem(value);
            }
            for value in std::mem::take(&mut node.body) {
                self.visit_stmt(value);
            }
        self.indent -= 1;
    }

    fn visit_type_param_param_spec(&mut self, mut node: TypeParamParamSpec<TextRange>) {
        self.emit(TypeParamParamSpec::<TextRange>::NAME, node.range(), Some(&[
            format_args!("{f} = {v:?}", f = "name", v = node.name.as_str()),
        ]));
    }

    fn visit_type_param_type_var(&mut self, mut node: TypeParamTypeVar<TextRange>) {
        self.emit(TypeParamTypeVar::<TextRange>::NAME, node.range(), Some(&[
            format_args!("{f} = {v:?}", f = "name", v = node.name.as_str()),
        ]));
        self.indent += 1;
            if let Some(value) = node.bound {
                self.visit_expr(*value);
            }
        self.indent -= 1;
    }

    fn visit_type_param_type_var_tuple(&mut self, mut node: TypeParamTypeVarTuple<TextRange>) {
        self.emit(TypeParamTypeVarTuple::<TextRange>::NAME, node.range(), Some(&[
            format_args!("{f} = {v:?}", f = "name", v = node.name.as_str()),
        ]));
    }

    fn visit_withitem(&mut self, mut node: WithItem<TextRange>) {
        self.emit(WithItem::<TextRange>::NAME, node.range(), None);
        self.indent += 1;
            self.visit_expr(node.context_expr);
            if let Some(value) = node.optional_vars {
                self.visit_expr(*value);
            }
        self.indent -= 1;
    }

}